---
# --- Set secrets ---
- set_fact:
    secret_data_mysql_password: "{{ lookup('file', 'secrets/mysql_password') }}"
    secret_data_django_secret_key: "{{ lookup('file', 'secrets/django_secret_key') }}"
    secret_data_recognizer_auth: "{{ lookup('file', 'secrets/recognizer_auth') }}"

- name: create pa3 directory
  file:
    path: "{{ build_directory }}"
    state: "directory"

- name: sync source
  synchronize:
    src: files/pa3_frontend/pa3_django
    dest: "{{ build_directory }}"

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "{{ build_directory }}"
  with_items:
    - files/pa3_frontend/crontab
    - files/pa3_frontend/Dockerfile
    - files/pa3_frontend/entrypoint.sh
    - files/pa3_frontend/requirements.txt

- name: Template files
  template:
    src: files/pa3_frontend/docker-compose.yml.j2
    dest: "{{ build_directory }}/docker-compose.yml"

- name: ensure .dockerignore
  copy:
    content: "^pa3_mysql/\n"
    dest: "{{ build_directory }}/.dockerignore"

- name: Make sure that the database-volume directory exists
  file:
    path: "{{ build_directory }}/mysql_data"
    state: "directory"

- name: ensure docker network
  docker_network:
    name: webproxy

- name: Start Services
  docker_service:
    project_src: "{{ build_directory }}"
    project_name: pa3
    state: present
    restarted: yes
    build: yes
