stages:
  - test
  - deploy

test_recognition:
  stage: test
  image: python:3.6
  before_script:
    - "pip -q install -r src/pa3_recognizer/recognition/requirements.txt"
  script:
    - "cd src/pa3_recognizer/recognition/"
    - "export PYTHONPATH=$(pwd)"
    - "python tests/test_number.py"
    - "python tests/test_digits_numbers.py"
    - "python tests/test_whole_algorithm.py"

deploy:
  stage: deploy
  image: williamyeh/ansible:debian9-onbuild
  before_script:
    - 'apt-get -qq update -y && DEBIAN_FRONTEND=noninteractive apt-get -qq install openssh-client -y &>/dev/null'
    - eval $(ssh-agent -s)
    - echo "$SSH_DEPLOY_PRIVATEKEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - echo "$SSH_DEPLOY_HOSTKEY" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts && chmod 700 ~/.ssh
  script:
    - "ansible-playbook -i hosts playbook.yml"

