stages:
  - test
  - deploy

test_recognition:
  stage: test
  image: python:3.6
  before_script:
    - "pip -q install -r src/pa3_recognizer/recognition/requirements.txt"
  script:
    - "cd src/pa3_recognizer/recognition/"
    - "export PYTHONPATH=$(pwd)"
    - "python tests/test_number.py"
    - "python tests/test_digits_numbers.py"
    - "python tests/test_whole_algorithm.py"
  except:
    - master

build_web:
  stage: deploy
  before_script:
    - docker login gitlab-registry.tubit.tu-berlin.de
  script:
    - docker build -t gitlab-registry.tubit.tu-berlin.de/freitagsrunde/pa3/pa3_frontend:latest
      -f src/pa3_frontend/Dockerfile_frontend
      --build-arg SECRET_RECOGNIZER_AUTH=$SECRET_RECOGNIZER_AUTH
      --build-arg SECRET_MYSQL_ROOT_PASSWORD=$SECRET_MYSQL_ROOT_PASSWORD
      --build-arg SECRET_DJANGO_KEY=$SECRET_DJANGO_KEY
      src/pa3_frontend
    - docker build -t gitlab-registry.tubit.tu-berlin.de/freitagsrunde/pa3/pa3_proxy:latest
      -f src/pa3_proxy/Dockerfile_proxy
      src/pa3_proxy
    - docker build -t gitlab-registry.tubit.tu-berlin.de/freitagsrunde/pa3/pa3_mysql:latest
      -f src/pa3_mysql/Dockerfile_mysql
      --build-arg SECRET_MYSQL_ROOT_PASSWORD=$SECRET_MYSQL_ROOT_PASSWORD
       src/pa3_mysql

    - docker push gitlab-registry.tubit.tu-berlin.de/freitagsrunde/pa3/pa3_frontend
    - docker push gitlab-registry.tubit.tu-berlin.de/freitagsrunde/pa3/pa3_proxy
    - docker push gitlab-registry.tubit.tu-berlin.de/freitagsrunde/pa3/pa3_mysql
