stages:
  - test
  - deploy

test_recognition:
  stage: test
  image: python:3.6
  before_script:
    - "pip -q install -r src/pa3_recognizer/recognition/requirements.txt"
  script:
    - "cd src/pa3_recognizer/recognition/"
    - "export PYTHONPATH=$(pwd)"
    - "python tests/test_number.py"
    - "python tests/test_digits_numbers.py"
    - "python tests/test_whole_algorithm.py"
  except:
    - master

build_web:
  stage: deploy
  image: williamyeh/ansible:debian9-onbuild
  script:
    - ansible-playbook --connection=local -vvv ansible/gitlab-ci_build_web.yml
