stages:
  - test
  - deploy

test_rec:
  stage: test
  image: python:3
  before_script:
    - "pip install -r src/pa3_recognizer/requirements.txt"
    -
  script:
    - "python src/pa3_recognizer/"

deploy_web:
  stage: deploy
  script: "cat file1.txt file2.txt | gzip > packaged.gz"

deploy_rec:
  stage: deploy
  script: "echo TODO"
