stages:
  - test
  - deploy

test_rec:
  stage: test
  image: python:3
  before_script:
    - "pip install -r src/pa3_recognizer/recognition/requirements.txt"

  script:
    - "cd src/pa3_recognizer/recognition/"
    - "python tests/testRecognitorTUB.py"
    - "python tests/testWholeAlgorithm.py"

deploy_web:
  stage: deploy
  script: "cat file1.txt file2.txt | gzip > packaged.gz"

deploy_rec:
  stage: deploy
  script: "echo TODO"
