stages:
  - test
  - deploy

test_recognition:
  stage: test
  image: python:3.6
  before_script:
    - "pip -q install -r src/pa3_recognizer/recognition/requirements.txt"
  script:
    - "cd src/pa3_recognizer/recognition/"
    - "export PYTHONPATH=$(pwd)"
    - "python tests/test_number.py"
    - "python tests/test_digits_numbers.py"
    - "python tests/test_whole_algorithm.py"

deploy:
  stage: deploy
  image: ansible
  script: "cat file1.txt file2.txt | gzip > packaged.gz"

