FROM python:3.6
ENV PYTHONUNBUFFERED 1
RUN mkdir /root/pa3
# ADD src/pa3_frontend/pa3 /root/pa3 # when finished. Now, mount rw volume for better setup first
# ADD src/secrets /root/pa3/    #TODO: check if correct folder-copy or single files

ADD src/pa3_frontend/requirements.txt /root/
RUN pip install -r /root/requirements.txt
