FROM python:3.4
ENV PYTHONUNBUFFERED 1

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y apache2 apache2-utils libapache2-mod-wsgi-py3 vim
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales gettext
RUN sed -i -e 's/# de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=de_DE.UTF-8
ENV LANG de_DE.UTF-8 

# Remove afterwards
RUN mkdir -p /etc/letsencrypt/live/pa3/
ADD data/frontend_certs /etc/letsencrypt/live/pa3/

ADD src/pa3_frontend/requirements.txt /root
# ADD src/pa3_frontend/pa3_django /srv/ # when finished. Now, mount rw volume for better setup first
# ADD data/secrets /srv/pa3_django/    #TODO: check if correct folder-copy or single files
ADD src/pa3_frontend/apache2-site.conf /etc/apache2/sites-enabled/000-default.conf
RUN a2enmod ssl

RUN pip3 install -r /root/requirements.txt
#RUN python3 /srv/pa3_django/manage.py collectstatic --noinput

EXPOSE 80 443

RUN touch /var/log/django_debug.log; chmod 777 /var/log/django_debug.log

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
#CMD ["/bin/bash"]
