FROM debian:latest

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server iptables

RUN mkdir /var/run/sshd
RUN mkdir /root/.ssh
RUN mkdir /root/current_images

COPY src/pa3_client/pa3_client_key.pub /root/.ssh/authorized_keys
COPY src/pa3_backend/commands.sh /root/commands.sh

CMD ["/bin/bash", "/root/commands.sh"]
