---
- name: Install docker on all hosts
  hosts: web
#  hosts: all
  tasks:
    - include_tasks: src/playbook_install_docker.yml


- name: Synchronize, build and run containers on the webhost
  hosts: web
  tasks:
    - include_tasks: src/pa3_frontend/playbook_tasks.yml
      vars:
        server_url: pa3.sistason.de
        build_directory: "/home/{{ ansible_user }}"
        subnet: 172.30.0


- name: Synchronize, build and run recognizer-containers on the recognizers
#  hosts: recognizers
  hosts: none
  connection: local
  tasks:
    - include_tasks: src/pa3_recognizer/playbook_tasks.yml
      vars:
        server_url: pa3.sistason.de
        build_directory: "/home/{{ ansible_user }}"
