---
- name: Install docker on all hosts
  hosts: web
#  hosts: all
  tasks:
    - include_tasks: src/playbook_install_docker.yml


- name: Setup secrets
  hosts: localhost
  connection: local
  tasks:
    - include_tasks: src/playbook_create_secrets.yml
      vars:
        secret_path_mysql_root_password: data/secrets/mysql_root_password
        secret_path_django_secret_key: data/secrets/django_secret_key
        secret_path_recognizer_auth: data/secrets/recognizer_auth


- name: Synchronize, build and run containers on the webhost
  hosts: web
  tasks:
    - include_tasks: src/pa3_frontend/playbook_tasks.yml
      vars:
        server_url: pa3.sistason.de
        build_directory: "/home/{{ ansible_user }}"
        #bind_ip: 172.31.37.208
        #bind_ip: 127.0.0.1


- name: Synchronize, build and run recognizer-containers on the recognizers
#  hosts: recognizers
  hosts: none
  connection: local
  tasks:
    - include_tasks: src/pa3_recognizer/playbook_tasks.yml
      vars:
        server_url: pa3.sistason.de
        build_directory: "/home/{{ ansible_user }}"
