FROM python:3.6

RUN mkdir -p /srv/pa3/current_images
RUN mkdir -p /run/secrets/

COPY recognizer_auth /run/secrets/
COPY recognition/ /srv/pa3/recognition

RUN pip install -r /srv/pa3/recognition/requirements.txt

CMD ["python", "/srv/pa3/recognition/paProj.py"]
