FROM sgtwilko/rpi-raspbian-opencv
#FROM python:3.6

RUN mkdir -p /srv/pa3/current_images
RUN mkdir -p /run/secrets/

COPY pa3_recognizer/recognizer_auth /run/secrets/
COPY pa3_recognizer/recognition/ /srv/pa3/recognition

RUN pip3 install -r /srv/pa3/recognition/requirements.txt

CMD ["python3", "/srv/pa3/recognition/waitingnumberrecognition.py"]
