---
- name: Copy pa3_recognizer src to the host
  synchronize:
    src: src/pa3_recognizer
    dest: "{{ build_directory }}"

- name: Copy necessary secrets
  synchronize:
    src: data/secrets/recognizer_auth
    dest: "{{ build_directory }}/pa3_recognizer/"

# Ansible-docker_build has poor performance and docker build already has the idempotence, so use the command-module here
- name: Build recognizer
  become: yes
  command: docker build -t pa3_recognizer:latest -f "{{ build_directory }}/pa3_recognizer/Dockerfile_recognizer" "{{ build_directory }}/pa3_recognizer"

- name: Start the recognizer container on the host
  become: yes
  docker_container:
    name: pa3_recognizer
    hostname: "pa3_{{ inventory_hostname }}"
    image: pa3_recognizer
    state: started
    devices:
      - "/dev/video0:/dev/video0:rwm"
    env:
      SERVER_URL: "{{ server_url }}"
      CAMERA: 0
      PYTHONPATH: "/srv/pa3/recognition"

