---
- name: create build-directory
  file:
    path: "{{ build_directory }}/build"
    state: "directory"

- name: Copy pa3_recognizer src to the host
  synchronize:
    src: "{{ item }}"
    dest: "{{ build_directory }}/build/"
  with_items:
    - files/pa3_recognizer/requirements.txt
    - files/pa3_recognizer/recognition
    - files/pa3_recognizer/Dockerfile
    - secrets/recognizer_auth

- name: Template docker-compose
  template:
    src: files/pa3_recognizer/docker-compose.yml.j2
    dest: "{{ build_directory }}/docker-compose.yml"

- docker_service:
    project_src: "{{ build_directory }}"
    state: present
    restarted: yes
    build: yes
