# Generated by Django 2.0.4 on 2018-04-12 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewestNumberBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(choices=[('pa_23', 'H 23'), ('pa_02', 'H 02'), ('pa_10', 'H 10'), ('pa_13', 'H 13')], max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StatisticalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(choices=[(['H 19', 'H 23', 'H 25'], ['H 19', 'H 23', 'H 25']), (['H 02'], ['H 02']), (['H 10'], ['H 10']), (['Schalter 1/2', 'Schalter 3/4', 'Schalter 5/6', 'Schalter 7/8/9', 'Schalter 10/11'], ['Schalter 1/2', 'Schalter 3/4', 'Schalter 5/6', 'Schalter 7/8/9', 'Schalter 10/11'])], max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('avg', models.FloatField(default=0.0)),
                ('avg_len', models.IntegerField(default=-1)),
                ('avg_sum', models.IntegerField(default=0)),
                ('avg_proc_delay_sum', models.IntegerField(default=0)),
                ('avg_proc_delay_len', models.IntegerField(default=-1)),
                ('avg_last_two_weeks', models.FloatField(default=0.0)),
                ('avg_last_same_day', models.FloatField(default=0.0)),
                ('avg_whole', models.FloatField(default=0.0)),
                ('avg_proc_delay_whole', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(choices=[(['H 19', 'H 23', 'H 25'], ['H 19', 'H 23', 'H 25']), (['H 02'], ['H 02']), (['H 10'], ['H 10']), (['Schalter 1/2', 'Schalter 3/4', 'Schalter 5/6', 'Schalter 7/8/9', 'Schalter 10/11'], ['Schalter 1/2', 'Schalter 3/4', 'Schalter 5/6', 'Schalter 7/8/9', 'Schalter 10/11'])], max_length=50)),
                ('date', models.DateTimeField()),
                ('date_delta', models.IntegerField(null=True)),
                ('proc_delay', models.FloatField(null=True)),
                ('number', models.SmallIntegerField()),
                ('statistic', models.ForeignKey(on_delete=None, to='pa3.StatisticalData')),
            ],
            options={
                'ordering': ['-date', 'src'],
            },
        ),
        migrations.CreateModel(
            name='WaitingNumberBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(choices=[('pa_23', 'H 23'), ('pa_02', 'H 02'), ('pa_10', 'H 10'), ('pa_13', 'H 13')], db_index=True, max_length=50)),
                ('src_ip', models.GenericIPAddressField()),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('date_delta', models.IntegerField(null=True)),
                ('proc_delay', models.FloatField(null=True)),
                ('numbers', models.ManyToManyField(to='pa3.WaitingNumber')),
            ],
            options={
                'ordering': ['-date', 'src'],
            },
        ),
        migrations.AddField(
            model_name='newestnumberbatch',
            name='newest',
            field=models.ForeignKey(on_delete=None, to='pa3.WaitingNumberBatch'),
        ),
    ]
