# Generated by Django 2.0.2 on 2018-02-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa3', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
