FROM python:3.6
ENV PYTHONUNBUFFERED 1

# Apache2-dev needed for mod_wsgi compilation by pip to get mod_wsgi for  3.6, not the 3.4 of debian
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y apache2 apache2-utils apache2-dev
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y cron vim
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales gettext
RUN sed -i -e 's/# de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=de_DE.UTF-8
ENV LANG de_DE.UTF-8 

# Copy secrets manually (not a swarm, no service-secrets available)
ARG SECRET_MYSQL_ROOT_PASSWORD
ARG SECRET_RECOGNIZER_AUTH
ARG SECRET_DJANGO_SECRET_KEY
RUN mkdir /run/secrets
RUN echo "$SECRET_RECOGNIZER_AUTH" > /run/secrets/recognizer_auth
RUN echo "$SECRET_MYSQL_ROOT_PASSWORD" > /run/secrets/mysql_root_password
RUN echo "$SECRET_DJANGO_SECRET_KEY" > /run/secrets/django_secret_key
RUN chown www-data:www-data /run/secrets/*

RUN chown www-data:www-data /dev/shm

COPY pa3_frontend/requirements.txt /root
RUN pip3 install -r /root/requirements.txt

COPY pa3_frontend/apache2-site.conf /etc/apache2/sites-enabled/000-default.conf
RUN mod_wsgi-express module-config | head -n1 >> /etc/apache2/apache2.conf
RUN mkdir -p /etc/apache2/ssl
RUN a2enmod ssl
EXPOSE 443

COPY pa3_frontend/crontab /etc/crontab
RUN touch /var/log/django_debug.log; chmod 777 /var/log/django_debug.log
COPY pa3_frontend/pa3_django /srv/pa3_django

COPY pa3_frontend/entrypoint.sh /srv/pa3_entrypoint.sh

WORKDIR /srv/pa3_django
ENTRYPOINT ["/bin/bash", "/srv/pa3_entrypoint.sh"]
