---
# Create web network, for better firewalling comfortability 
- name: Create network
  docker_network:
    name: pa3_net
    driver: bridge
    driver_options:
      com.docker.network.bridge.name: pa3-docker-br
    ipam_options:
      subnet: '172.17.0.0/28'

# Copy src
- name: create pa3 directory
  file: 
    path: "{{ frontend_directory }}" 
    state: "directory"

- name: Copy frontent to the host
  synchronize:
    src: src/pa3_frontend
    dest: "{{ frontend_directory }}"
    rsync_opts:
      - "--exclude=apache2-site.conf.j2"

- name: Copy apache2-config with server_url
  template:
    src: src/pa3_frontend/apache2-site.conf.j2
    dest: "{{ frontend_directory }}/pa3_frontend/apache2-site.conf"

- name: Copy proxy to the host
  synchronize:
    src: src/pa3_proxy
    dest: "{{ frontend_directory }}/"
    rsync_opts:
      - "--exclude=proxy.conf.j2"

- name: Copy nginx-proxy-config with server_url
  template:
    src: src/pa3_proxy/proxy.conf.j2
    dest: "{{ frontend_directory }}/pa3_proxy/proxy.conf"

#- name: Copy necessary secrets
#  synchronize:
#    src: data/secrets
#    dest: "{{ frontend_directory }}/"

- name: Copy .dockerignore
  synchronize:
    src: .dockerignore
    dest: "{{ frontend_directory }}/"

# Build containers 
# docker build already has the idempotence, so use the command-module here
- name: Build frontend
  command: "docker build -t pa3_frontend:latest -f {{ frontend_directory }}/pa3_frontend/Dockerfile_frontend {{ frontend_directory }}"

- name: Build proxy
  command: "docker build -t pa3_proxy:latest -f {{ frontend_directory }}/pa3_proxy/Dockerfile_proxy {{ frontend_directory }}/pa3_proxy"

# Start web containers
- name: Make sure that the database-volume directory exists
  file: 
    path: "{{ frontend_directory }}/mysql"
    state: "directory"

#- name: chown the secret to mysql (999), as it gets rsynced and has unknown permissions
#   become_user: root
#  file:
#    path: "{{ frontend_directory }}/secrets/mysql_root_password"
#    owner: 999
#    group: 999

- name: Start mysql container
  docker_container:
    name: pa3_mysql
    hostname: pa3_mysql
    image: mysql
    state: started
    networks:
      - name: "pa3_net"
    volumes:
      - "{{ frontend_directory }}/mysql:/var/lib/mysql:rw"
      - "{{ frontend_directory }}/secrets/mysql_root_password:/run/secrets/mysql_root_password:rw"
    env:
      MYSQL_DATABASE: "pa3_django"
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql_root_password"

- name: Make sure the certificates-directory exists
  file:
    path: "{{ frontend_directory }}/letsencrypt"
    state: "directory"

- name: Start letsencrypt proxy container
  docker_container:
    name: pa3_proxy
    image: pa3_proxy
    command: "{{ server_url }}"
    networks:
      - name: "pa3_net"
    ports:
        - "80:80"
    volumes:
      - "{{ frontend_directory }}/letsencrypt:/etc/letsencrypt:rw"

- name: Start frontend container
  docker_container:
    name: pa3_frontend
    hostname: pa3_frontend
    image: pa3_frontend
    state: started
    networks:
      - name: "pa3_net"
    ports:
      - "443:443"
    volume_driver: bind
    volumes:
      - "{{ frontend_directory }}/letsencrypt/archive:/etc/apache2/ssl:rw"
      # TODO: remove in production. For coding without compiling first
      - "/home/sistason/skriptecke/pa3/src/pa3_frontend/pa3_django:/srv/pa3_django:rw"

