---
- hosts: localhost
  connection: local
  roles:
    - docker
  tasks:
    - name: Template the cron-script
      template:
        src: ../src/pa3_frontend/update_script.sh.j2
        dest: ../src/pa3_frontend/update_script.sh

    - name: Copy apache2-config with server_url
      template:
        src: ../src/pa3_frontend/apache2-site.conf.j2
        dest: ../src/pa3_frontend/apache2-site.conf

    - name: Copy nginx-proxy-config with server_url
      template:
        src: ../src/pa3_proxy/proxy.conf.j2
        dest: ../src/pa3_proxy/proxy.conf

    - name: Build frontend
      command: "docker build -t gitlab-registry.tubit.tu-berlin.de/freitagsrunde/pa3/pa3_frontend:latest
        -f ../src/pa3_frontend/Dockerfile_frontend
        --build-arg SECRET_RECOGNIZER_AUTH=\"{{ lookup('env', 'SECRET_RECOGNIZER_AUTH') }}\"
        --build-arg SECRET_MYSQL_ROOT_PASSWORD=\"{{ lookup('env', 'SECRET_MYSQL_ROOT_PASSWORD') }}\"
        --build-arg SECRET_DJANGO_KEY=\"{{ lookup('env', 'SECRET_DJANGO_SECRET_KEY') }}\"
        ../src"

    - name: Build proxy
      command: "docker build -t gitlab-registry.tubit.tu-berlin.de/freitagsrunde/pa3/pa3_proxy:latest
        -f ../src/pa3_proxy/Dockerfile_proxy
        ../src"

    - name: Build mysql
      command: "docker build -t gitlab-registry.tubit.tu-berlin.de/freitagsrunde/pa3/pa3_mysql:latest
        -f ../src/pa3_mysql/Dockerfile_mysql
        --build-arg SECRET_MYSQL_ROOT_PASSWORD={{ lookup('env', 'SECRET_MYSQL_ROOT_PASSWORD') }}
        ../src"

    - name: Push frontend
      docker_image:
        name: gitlab-registry.tubit.tu-berlin.de/freitagsrunde/pa3/pa3_frontend
        push: yes

    - name: Push proxy
      docker_image:
        name: gitlab-registry.tubit.tu-berlin.de/freitagsrunde/pa3/pa3_proxy
        push: yes

    - name: Push mysql
      docker_image:
        name: gitlab-registry.tubit.tu-berlin.de/freitagsrunde/pa3/pa3_mysql
        push: yes
