---
- hosts: localhost
  connection: local
  roles:
    - docker
  tasks:
    - name: Template the cron-script
      template:
        src: ../src/pa3_frontend/update_script.sh.j2
        dest: ../src/pa3_frontend/update_script.sh

    - name: Copy apache2-config with server_url
      template:
        src: ../src/pa3_frontend/apache2-site.conf.j2
        dest: ../src/pa3_frontend/apache2-site.conf

    - name: Copy nginx-proxy-config with server_url
      template:
        src: ../src/pa3_proxy/proxy.conf.j2
        dest: ../src/pa3_proxy/proxy.conf
