---
- name: Get the secrets from the webserver and initialize empty ones
  hosts: web
  tasks:
  - name: create secrets directory
    file:
      path: "{{ build_directory }}/secrets"
      state: directory

  - name: secret_path_mysql_root_password exists?
    stat:
      path: "{{ build_directory }}/secrets/mysql_root_password"
    register: exists
  - name: delete pw file if empty, as the lookup_password uses an empty pw otherwise
    when: exists.stat.size is defined and exists.stat.size < 4
    file:
      path: "{{ build_directory }}/secrets/mysql_root_password"
      state: absent

  - name: secret_path_django_secret_key exists?
    stat:
      path: "{{ build_directory }}/secrets/django_secret_key"
    register: exists
  - name: delete pw file if empty, as the lookup_password uses an empty pw otherwise
    when: exists.stat.size is not defined or exists.stat.size < 4
    file:
      path: "{{ build_directory }}/secrets/django_secret_key"
      state: absent

  - name: secret_path_recognizer_auth exists?
    stat:
      path: "{{ build_directory }}/secrets/recognizer_auth"
    register: exists
  - name: delete pw file if empty, as the lookup_password uses an empty pw otherwise
    when: exists.stat.size is not defined or exists.stat.size < 4
    file:
      path: "{{ build_directory }}/secrets/recognizer_auth"
      state: absent

  - name: Copy secrets to localhost for the next playbooks and for the password-lookup
    synchronize:
      mode: pull
      src: "{{ build_directory }}/secrets"
      dest: "."

  # only build passwords, the facts don't matter
  - set_fact:
      secret_data_mysql_root_password: "{{ lookup('password', 'secrets/mysql_root_password length=32') }}"
      secret_data_django_secret_key: "{{ lookup('password', 'secrets/django_secret_key length=32') }}"
      secret_data_recognizer_auth: "{{ lookup('password', 'secrets/recognizer_auth length=32') }}"

  - name: Copy secrets again to have them with content now. Thank you password-lookups only working on localhost
    synchronize:
      src: secrets
      dest: "{{ build_directory }}/"