---
# Adapted from nickjj/ansible-docker
- name: Install Docker and role dependencies
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: "present"
    install_recommends: False
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "software-properties-common"
    - "python-docker"

- name: Get upstream APT GPG key
  become: yes
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    keyserver: "{{ ansible_local.core.keyserver
                   if (ansible_local|d() and ansible_local.core|d() and
                       ansible_local.core.keyserver)
                   else 'hkp://pool.sks-keyservers.net' }}"
    state: "present"

- name: get packet_architecture
  set_fact:
    architecture: "{{ 'armhf' if ansible_machine.startswith('arm') else 'amd64' }}"

- name: Configure upstream APT repository
  become: yes
  apt_repository:
    repo: "deb [arch={{ architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} edge"
    state: "present"
    update_cache: True

- name: Install Docker
  become: yes
  apt:
    name: "docker-ce"
    state: "present"
    update_cache: True
    install_recommends: False
    cache_valid_time: "86400"



