# Generated by Django 2.0.4 on 2018-04-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(choices=[('FR', 'FR'), ('PA', 'PA')], max_length=2)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
