# Generated by Django 2.0.4 on 2018-04-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa3_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(choices=[(['H 10'], ['H 10']), (['Schalter 1/2', 'Schalter 3/4', 'Schalter 5/6', 'Schalter 7/8/9', 'Schalter 10/11'], ['Schalter 1/2', 'Schalter 3/4', 'Schalter 5/6', 'Schalter 7/8/9', 'Schalter 10/11']), (['H 02'], ['H 02']), (['H 19', 'H 23', 'H 25'], ['H 19', 'H 23', 'H 25'])], max_length=50)),
                ('identifier', models.CharField(max_length=200)),
                ('number', models.SmallIntegerField()),
                ('buffer', models.SmallIntegerField()),
            ],
        ),
    ]
