# Generated by Django 2.0.4 on 2018-04-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa3_web', '0007_auto_20180413_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='src',
            field=models.CharField(choices=[(['H 19', 'H 23', 'H 25'], ['H 19', 'H 23', 'H 25']), (['H 10'], ['H 10']), (['H 02'], ['H 02']), (['Schalter 1/2', 'Schalter 3/4', 'Schalter 5/6', 'Schalter 7/8/9', 'Schalter 10/11'], ['Schalter 1/2', 'Schalter 3/4', 'Schalter 5/6', 'Schalter 7/8/9', 'Schalter 10/11'])], max_length=50),
        ),
    ]
